=== Jo-dle/E2_UF2218_Joel/xml/coches.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="coches">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"/>
                            <xs:element name="modelo" type="xs:string"/>
                            <xs:element name="puertas">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="2"/>
                                        <xs:maxInclusive value="5"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="color" type="xs:string"/>
                            <xs:element name="precio">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:integer">
                                            <xs:attribute name="venta" use="required">
                                                <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                        <xs:enumeration value="nuevo"/>
                                                        <xs:enumeration value="ocasión"/>
                                                        <xs:enumeration value="segunda mano"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="matricula" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[0-9]{4}[A-Z]{3}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Jo-dle/E2_UF2218_Joel/xml/coches.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="coches.xsl"?>
<coches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./coches.xsd">
  <coche matricula="0001DEF">
    <marca>Volkswagen</marca>
    <modelo>Golf</modelo>
    <puertas>5</puertas>
    <color>Negro</color>
    <precio venta="segunda mano">9800</precio>
  </coche>
  <coche matricula="5678AFG">
    <marca>Audi</marca>
    <modelo>10</modelo>
    <puertas>5</puertas>
    <color>Guinda</color>
    <precio venta="nuevo">10000</precio>
  </coche>
  <coche matricula="5656FFF">
    <marca>Fredolsen</marca>
    <modelo>el de ayer</modelo>
    <puertas>2</puertas>
    <color>amarillo</color>
    <precio venta="nuevo">454</precio>
  </coche>
  <coche matricula="1234RTY">
    <marca>Toyota</marca>
    <modelo>el de ayer</modelo>
    <puertas>2</puertas>
    <color>Guinda</color>
    <precio venta="nuevo">45874</precio>
  </coche>
</coches>
